name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  jiffy: ^2.1.2
  flutter_icons: ^1.0.0+1
  charts_flutter: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Jost
      fonts:
        - asset: third_party/Jost/TrueType/Jost-100-Hairline.ttf
          weight: 100
        - asset: third_party/Jost/TrueType/Jost-200-Thin.ttf
          weight: 200
        - asset: third_party/Jost/TrueType/Jost-300-Light.ttf
          weight: 300
        - asset: third_party/Jost/TrueType/Jost-400-Book.ttf
          weight: 400
        - asset: third_party/Jost/TrueType/Jost-500-Medium.ttf
          weight: 500
        - asset: third_party/Jost/TrueType/Jost-600-Semi.ttf
          weight: 600
        - asset: third_party/Jost/TrueType/Jost-700-Bold.ttf
          weight: 700
        - asset: third_party/Jost/TrueType/Jost-800-Heavy.ttf
          weight: 800
        - asset: third_party/Jost/TrueType/Jost-900-Black.ttf
          weight: 900

